[package]
name = "rusty_music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bevy_fundsp = { git="https://github.com/lavaeater/bevy_fundsp.git", branch = "bevy-0.13"}
uuid = { version = "1.7.0", features = ["v4"] }

[profile.dev.package."*"]
opt-level = 3
